Repository Zendro-dev/graphql-server, pull requests merged in 2021-05, with the labels that each got.

#64 fix: jwt fix
  .gitignore
  config/globals.js
  package-lock.json
  package.json
  server.js
  utils/check-authorization.js
  utils/helpers-acl.js
Labels: bug

#63 refactor: Metaquery refactor
  .gitignore
  config/globals.js
  package-lock.json
  package.json
  server.js
  utils/check-authorization.js
  utils/helpers-acl.js
Labels: enhancement

#65 Presto
  config/data_models_storage_config.json
  connection.js
  models/adapters/index.js
  models/index.js
  package.json
  utils/helper.js
  utils/presto_helper.js
  utils/search-argument.js
Labels: enhancement

#66 feat: mandatory environment variables
  README.md
  config/globals.js
  utils/email.js
Labels: enhancement

#67 feat: remove extra checkAuthorization from meta_query endpoint
  server.js
Labels: bug, enhancement
